# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean clover:setup clover:clover clover:aggregate'
  displayName: 'Unit Tests and Coverage'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'dependency-check:aggregate'
    publishJUnitResults: false
  displayName: 'OWASP Dependency Check'
- task: PublishBuildArtifacts@1
  displayName: 'Publish OWASP Dependency Check Report'
  inputs:
    ArtifactName: 'OWASP Dependency Check Report'
    PathtoPublish: '$(Build.SourcesDirectory)/target/dependency-check'
