apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-demo
  namespace: demo
  labels:
    app: kube-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-demo
  template:
    metadata:
      labels:
        app: kube-demo
    spec:
      containers:
        - name: kube-demo
          image: kube-demo:1.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 5
          #   periodSeconds: 5
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 35
          #   timeoutSeconds: 5
          #   periodSeconds: 10
          #   failureThreshold: 1
          # env:
          # - name: SPRING_CONFIG_LOCATION
          #   value: classpath:application.properties,file:/home/kube-demo/config/
          # - name: SPRING_PROFILES_ACTIVE
          #   value: prod
          # - name: SPRING_DATASOURCE_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: kube-demo
          #       key: mysql-password
          # volumeMounts:
          #   - mountPath: /home/kube-demo/config
          #     name: kube-demo
      # volumes:
      # - configMap:
      #     name: kube-demo
      #   name: kube-demo
