apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-demo
  namespace: demo
  labels:
    app: kube-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-demo
  template:
    metadata:
      labels:
        app: kube-demo
    spec:
      containers:
        - name: kube-demo
          image: kube-demo:1.0
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # env:
          # - name: SPRING_PROFILES_ACTIVE
          #   value: dev
          # - name: SPRING_CONFIG_LOCATION
          #   value: classpath:application.properties,file:/home/kube-demo/config/
          # - name: SPRING_DATASOURCE_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: kube-demo
          #       key: mysql-password
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 2
          #   periodSeconds: 3
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 35
          #   timeoutSeconds: 2
          #   periodSeconds: 8
          #   failureThreshold: 1
          # volumeMounts:
          #   - mountPath: /home/kube-demo/config
          #     name: kube-demo
      # volumes:
      # - configMap:
      #     name: kube-demo
      #   name: kube-demo
